#!/usr/bin/env node
// Inline scripts/common/*.js fragments into the .user.js release files.
//
// Each .user.js marks inline regions like:
//     // ==INLINE common/ui.js==
//     // ==/INLINE==
// and this script fills the region with the common file's content, indented
// to match the marker. Run `node scripts/build.js` after editing common/;
// `node scripts/build.js --check` verifies the releases are in sync.

const fs = require('fs');
const path = require('path');

const scriptsDir = __dirname;
const checkOnly = process.argv.includes('--check');

const BLOCK_RE = /^([ \t]*)\/\/ ==INLINE (common\/[\w.-]+\.js)==[ \t]*\r?\n[\s\S]*?^[ \t]*\/\/ ==\/INLINE==[ \t]*$/gm;

function renderBlock(indent, relativePath) {
    const sourcePath = path.join(scriptsDir, relativePath);

    if (!fs.existsSync(sourcePath)) {
        throw new Error(`inline target not found: ${relativePath}`);
    }

    const source = fs.readFileSync(sourcePath, 'utf8').replace(/\r\n/g, '\n').trimEnd();
    const indented = source
        .split('\n')
        .map((line) => (line.trim() ? indent + line : ''))
        .join('\n');

    return `${indent}// ==INLINE ${relativePath}==\n`
        + `${indent}// Generated by scripts/build.js — edit scripts/${relativePath} instead.\n`
        + `${indented}\n`
        + `${indent}// ==/INLINE==`;
}

function buildFile(filePath) {
    const original = fs.readFileSync(filePath, 'utf8');
    let replaced = false;
    const built = original.replace(BLOCK_RE, (_match, indent, relativePath) => {
        replaced = true;
        return renderBlock(indent, relativePath);
    });

    if (!replaced) {
        return { filePath, status: 'no-markers' };
    }

    if (built === original) {
        return { filePath, status: 'unchanged' };
    }

    if (checkOnly) {
        return { filePath, status: 'stale' };
    }

    fs.writeFileSync(filePath, built);
    return { filePath, status: 'updated' };
}

const targets = fs.readdirSync(scriptsDir)
    .filter((name) => name.endsWith('.user.js'))
    .map((name) => path.join(scriptsDir, name));

let failed = false;

for (const target of targets) {
    try {
        const { status } = buildFile(target);
        const name = path.basename(target);

        if (status === 'stale') {
            console.error(`STALE     ${name} (run: node scripts/build.js)`);
            failed = true;
        } else if (status !== 'no-markers') {
            console.log(`${status.toUpperCase().padEnd(9)} ${name}`);
        }
    } catch (error) {
        console.error(`ERROR     ${path.basename(target)}: ${error.message}`);
        failed = true;
    }
}

if (failed) {
    process.exitCode = 1;
}
